### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [JamesLaverack/bernkastel#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by JamesLaverack** [comment]
Hey @unixorn. I think I must have missed the notification on this one. I've added a screenshot to the README. Sorry for the delay. 😅
